#!/usr/bin/python3
# Read in backups of /etc/passwd, group, shadow, gshadow and create new versions

import sys
import os

MIN_IMPORT_UID = 1000
USERNAMES_EXCLUDED = ['nobody', 'root']
GROUPNAMES_EXCLUDED = ['nobody', 'root', 'wheel']

def convertifint(val):
    '''Convert to integer if possible'''
    try:
        return int(val)
    except ValueError:
        return val

def write_shadow_line(outputfile, line, seen_x):
    xname = line.strip().split(':')[0]
    if xname in seen_x:
        outputfile.write(line)

def main():
    seen_gids = []
    seen_users = []
    seen_groups = []

    with open('passwd', 'r') as passwdfile, open('passwd_to_append.txt', 'w') as outputfile:
        for line in passwdfile:
            # Username, UID and GID are positions 0, 2 and 3 in /etc/passwd
            username, uid, gid = (convertifint(val) for val in (line.strip().split(':')[i] for i in (0,2,3)))
            if not username in USERNAMES_EXCLUDED:
                if uid >= MIN_IMPORT_UID:
                    seen_users.append(username)
                    seen_gids.append(gid)
                    outputfile.write(line)

    with open('shadow', 'r') as shadowfile, open('shadow_to_append.txt', 'w') as outputfile:
        for line in shadowfile:
            write_shadow_line(outputfile, line, seen_users)

    with open('group', 'r') as groupfile, open('group_to_append.txt', 'w') as outputfile:
        for line in groupfile:
            # Groupname ane GID are positions 0 and 2 /etc/group
            groupname, gid = (convertifint(val) for val in (line.strip().split(':')[i] for i in (0,2)))
            if not groupname in GROUPNAMES_EXCLUDED:
                if gid >= MIN_IMPORT_UID or gid in seen_gids:
                    seen_groups.append(groupname)
                    outputfile.write(line)

    with open('gshadow', 'r') as gshadowfile, open('gshadow_to_append.txt', 'w') as outputfile:
        for line in gshadowfile:
            write_shadow_line(outputfile, line, seen_groups)

if __name__ == "__main__":
    main()