#!/usr/bin/python3
# Read in backups of /etc/passwd, group, shadow, gshadow and create new versions

import sys
import os

MIN_IMPORT_UID = 1000
USERNAMES_EXCLUDED = ['nobody', 'root']
GROUPNAMES_EXCLUDED = ['nobody', 'root', 'wheel']

def convertifint(val):
    '''Convert to integer if possible'''
    try:
        return int(val)
    except ValueError:
        return val

def main():
    basedir = os.getcwd()

    seen_gids = []
    seen_users = []
    seen_groups = []

    with open('passwd', 'r') as passwdfile, open('passwd_to_append.txt', 'w') as outputfile:
        for line in passwdfile:
            username, NA, uid, gid, extra = (convertifint(val) for val in line.strip().split(':', 4))
            if not username in USERNAMES_EXCLUDED:
                if uid >= MIN_IMPORT_UID:
                    seen_users.append(username)
                    seen_gids.append(gid)
                    outputfile.write(line)

    with open('shadow', 'r') as shadowfile, open('shadow_to_append.txt', 'w') as outputfile:
        for line in shadowfile:
            username = line.strip().split(':')[0]
            if username in seen_users:
                outputfile.write(line)

    with open('group', 'r') as groupfile, open('group_to_append.txt', 'w') as outputfile:
        for line in groupfile:
            groupname, NA, gid, extra = (convertifint(val) for val in line.strip().split(':', 3))
            if not groupname in GROUPNAMES_EXCLUDED:
                if gid >= MIN_IMPORT_UID or gid in seen_gids:
                    seen_groups.append(groupname)
                    outputfile.write(line)

    with open('gshadow', 'r') as gshadowfile, open('gshadow_to_append.txt', 'w') as outputfile:
        for line in gshadowfile:
            groupname = line.strip().split(':')[0]
            if groupname in seen_groups:
                outputfile.write(line)

if __name__ == "__main__":
    main()